name: Update t1.json from ZIP Filename

on:
  # 每30分钟运行一次
  schedule:
    - cron: '*/30 * * * *'
  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 添加额外的依赖（如果有）

      - name: Run t1.py
        run: |
          python t1.py

      - name: Save generated files  # 将生成的文件上传为工作流构件
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: pgdown/t1.json

      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pgdown/t1.json
          git commit -m "Update t1.json from GitHub Actions" || true  # 如果没有新的 commit，忽略错误
          git push
